export const sistecFields = {
	uf: "",
	municipio: "",
	unidadeEnsino: "",
	codigoUnidadeEnsino: "",
	codigoInstituicao: "",
	subtipoCurso: "",
	codigoCurso: "",
	curso: "",
	cargaHorariaMinima: "",
	oferta: "",
	codigoCicloMatricula: "",
	cicloMatricula: "",
	cargaHorariaTotal: "",
	dataInicioCurso: "",
	dataFimPrevistoCurso: "",
	modalidadeEnsino: "",
	statusCicloMatricula: "",
	situacaoCiclo: "",
	tipoOfertaCurso: "",
	estagio: "",
	cargaHorariaEstagio: "",
	projetoPedagogico: "",
	situacaoETEC: "",
	codigoPortfolio: "",
	codigoPolo: "",
	qtdVagas: "",
	qtdInscritos: "",
	qtdMatriculas: "",
	dataCriacao: "",
	nomeResponsavel: "",
	cpf: "",
};

export const suapFields = {
	nome: "",
	campus: "",
	curso: "",
	situacaoCurso: "",
	situacaoUltimoPeriodo: "",
	nivelEnsino: "",
	modalidade: "",
	codigoEMEC: "",
	anoIngresso: "",
	periodoIngresso: "",
	anoConclusao: "",
	cpf: "",
	cotaMEC: "",
	cotaSISTEC: "",
	dataMatricula: "",
	dataConclusao: "",
	turno: "",
	vinculo: "",
	diariosMatriculasUltimoPeriodo: ""
};
